#!/usr/bin/env python3

import argparse
import json
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed


def get_instance_region(profile, region, instance_id):
    cmd = [
        "aws",
        "ec2",
        "describe-instances",
        "--instance-ids",
        instance_id,
        "--region",
        region,
    ]
    if profile:
        cmd.extend(["--profile", profile])
    try:
        output = subprocess.check_output(
            cmd, stderr=subprocess.PIPE, universal_newlines=True
        )
        response = json.loads(output)
        return response
    except subprocess.CalledProcessError as e:
        if "InvalidInstanceID.NotFound" in str(e.stderr):
            return None
        else:
            raise e


def get_instance_regions(profile, instance_ids):
    cmd = [
        "aws",
        "ec2",
        "describe-regions",
        "--query",
        "Regions[].{RegionName:RegionName}",
        "--output",
        "json",
    ]
    if profile:
        cmd.extend(["--profile", profile])
    regions = [
        x["RegionName"]
        for x in json.loads(subprocess.check_output(cmd, universal_newlines=True))
    ]

    instance_responses = []
    for instance_id in instance_ids:
        with ThreadPoolExecutor(max_workers=5) as executor_region:
            region_futures = {
                executor_region.submit(
                    get_instance_region, profile, region, instance_id
                ): region
                for region in regions
            }
            for future in as_completed(region_futures):
                result = future.result()
                if result:
                    instance_responses.append(result)
                    break
    return instance_responses


def stop_instance(instance_id, profile, region):
    cmd = [
        "aws",
        "ec2",
        "stop-instances",
        "--instance-ids",
        instance_id,
        "--region",
        region,
    ]
    if profile:
        cmd.extend(["--profile", profile])
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)
    print(f"{instance_id} in {region} has been stopped")


def start_instance(instance_id, profile, region):
    cmd = [
        "aws",
        "ec2",
        "start-instances",
        "--instance-ids",
        instance_id,
        "--region",
        region,
    ]
    if profile:
        cmd.extend(["--profile", profile])
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)
    print(f"{instance_id} in {region} has been started")


def terminate_instance(instance_id, profile, region):
    cmd = [
        "aws",
        "ec2",
        "terminate-instances",
        "--instance-ids",
        instance_id,
        "--region",
        region,
    ]
    if profile:
        cmd.extend(["--profile", profile])
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)
    print(f"{instance_id} in {region} has been terminated")


def process_instance_data(response, profile, args):
    for reservation in response.get("Reservations", []):
        for instance in reservation["Instances"]:
            instance_id = instance["InstanceId"]
            state = instance["State"]["Name"]
            availability_zone = instance["Placement"]["AvailabilityZone"]
            region = availability_zone[:-1]

            print(f"{instance_id} in ({availability_zone}) has a state of [{state}]")

            if args.stop:
                stop_instance(instance_id, profile, region)
            elif args.run:
                start_instance(instance_id, profile, region)
            elif args.terminate:
                terminate_instance(instance_id, profile, region)

                # Refresh instance state
                refreshed_response = get_instance_region(profile, region, instance_id)
                refreshed_instance = refreshed_response["Reservations"][0]["Instances"][
                    0
                ]
                refreshed_state = refreshed_instance["State"]["Name"]
                print(
                    f"{instance_id} in ({availability_zone}) has a NEW state of [{refreshed_state}]"
                )

            print("-" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Manage EC2 instances",
        formatter_class=argparse.RawTextHelpFormatter,
        epilog="""Examples:
# Get the running state and availability zone of EC2 instances
ec2-state -p my-profile -i i-1234567890abcdef0,i-0987654321fedcba0

# Use a specific AWS profile
ec2-state -p my-profile -i i-1234567890abcdef0

# Stop instances
ec2-state -s -p my-profile -i i-1234567890abcdef0,i-0987654321fedcba0

# Start instances
ec2-state -r -p my-profile -i i-1234567890abcdef0,i-0987654321fedcba0

# Terminate instances
ec2-state -t -p my-profile -i i-1234567890abcdef0,i-0987654321fedcba0

# Specify region explicitly
ec2-state -p my-profile -i i-1234567890abcdef0 --region us-west-2
""",
    )
    parser.add_argument("-p", "--profile", required=True, help="AWS profile to use")
    parser.add_argument("-s", "--stop", action="store_true", help="Stop instances")
    parser.add_argument(
        "-t", "--terminate", action="store_true", help="Terminate instances"
    )
    parser.add_argument("-r", "--run", action="store_true", help="Start instances")
    parser.add_argument(
        "-i", "--instances", required=True, help="Comma separated list of instance IDs"
    )
    parser.add_argument("--region", help="AWS region to use")

    args = parser.parse_args()

    # Set AWS profile
    profile = args.profile

    # Set instance IDs
    instance_ids = args.instances.split(",")

    # Check if a region was specified
    if args.region:
        # Use the specified region and don't get instance regions
        instance_responses = [
            get_instance_region(profile, args.region, instance_id)
            for instance_id in instance_ids
        ]
    else:
        # Get instance regions and perform actions concurrently
        print("Now finding regions for your instances...", end="", flush=True)
        instance_responses = get_instance_regions(profile, instance_ids)
        print(" ...done")
        print("-" * 60)

    # Process instance data
    for response in instance_responses:
        if response is None:
            continue
        process_instance_data(response, profile, args)


if __name__ == "__main__":
    main()
