#!/usr/bin/env python3

import argparse
import os
import shutil


def get_dir_size(path):
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            total_size += os.path.getsize(fp)
    return total_size / (1024 * 1024 * 1024)


def delete_terraform_files(path):
    total_saved_space = 0
    found_files = False
    for root, dirs, files in os.walk(path):
        for file in files:
            if file == ".terraform.lock.hcl":
                file_path = os.path.join(root, file)
                file_size = os.path.getsize(file_path) / (1024 * 1024 * 1024)
                os.remove(file_path)
                total_saved_space += file_size
                print(f"Deleted file {file_path} ({file_size:.2f} GB)")
                found_files = True
        for dir in dirs:
            if dir == ".terraform":
                dir_path = os.path.join(root, dir)
                dir_size = get_dir_size(dir_path)
                shutil.rmtree(dir_path)
                total_saved_space += dir_size
                print(f"Deleted directory {dir_path} ({dir_size:.2f} GB)")
                found_files = True
    if found_files:
        if total_saved_space >= 1024:
            total_saved_space /= 1024
            unit = "TB"
        else:
            unit = "GB"
        print(f"Total saved space: {total_saved_space:.2f} {unit}")
    else:
        print("No .terraform.lock.hcl files or .terraform directories found.")


if __name__ == "__main__":
    print("[TFDEL] Starting...")
    parser = argparse.ArgumentParser(
        description="Delete .terraform.lock.hcl files and .terraform directories recursively."
    )
    parser.add_argument(
        "path",
        metavar="path",
        type=str,
        nargs="?",
        default=".",
        help="the path to the directory to search (default: current working directory)",
    )
    args = parser.parse_args()
    path = args.path
    print(f"[TFDEL] Searching path: {path}")
    delete_terraform_files(path)
