#!/usr/bin/env python3

import argparse
import os
import re
import sys
from urllib.parse import urlparse

import requests


def parse_git_credentials(github_instance):
    creds_path = os.path.expanduser("~/.git-credentials")
    with open(creds_path, "r") as creds_file:
        creds = creds_file.read().strip()
    match = re.search(rf"https?://(.*):(.*)@{github_instance}", creds)
    if match:
        return match.group(1), match.group(2)
    else:
        raise Exception(f"Failed to parse .git-credentials for {github_instance}")


def delete_all_comments(pr_url, user, token):
    # Clean up the url and get the necessary parts
    parsed_url = urlparse(pr_url)
    base_url = (
        "api.github.com"
        if parsed_url.netloc == "github.com"
        else f"{parsed_url.netloc}/api/v3"
    )
    owner, repo, _, number = parsed_url.path.strip("/").split("/")

    # Get all comments on the pull request (paginated)
    url = f"https://{base_url}/repos/{owner}/{repo}/issues/{number}/comments"
    headers = {"Authorization": f"token {token}"}
    comments = []
    while url:
        response = requests.get(url, headers=headers, params={"per_page": 100})
        response.raise_for_status()
        comments.extend(response.json())
        url = response.links.get("next", {}).get("url")

    # Delete all comments
    for comment in comments:
        comment_url = comment["url"]
        print(f'Deleting comment: {comment["body"]}')
        response = requests.delete(comment_url, headers=headers)
        if response.status_code == 204:
            print(f'Successfully deleted comment: {comment["body"]}')
        else:
            print(
                f'Failed to delete comment: {comment["body"]}. Error: {response.text}'
            )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Delete all comments on a GitHub pull request",
        epilog="Note: Use the -h or --help option to display this help message.",
    )
    parser.add_argument(
        "pr_url", nargs="?", help="The URL of the pull request to delete comments from"
    )
    args = parser.parse_args()

    if not args.pr_url:
        parser.print_help()
        sys.exit(0)

    parsed_url = urlparse(args.pr_url)
    if parsed_url.netloc == "github.com":
        github_instance = "github.com"
    else:
        github_instance = parsed_url.netloc

    user, token = parse_git_credentials(github_instance)
    try:
        delete_all_comments(args.pr_url, user, token)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
